### ISSUE TITLE
NUTS implementation

### ISSUE THREAD

**Issue by xukai92** [yebai/Turing.jl#188]
Before implementing the NUTS sampler I think it's better for us to clear up the following issues:

- [x] #174 Merge `ParticleSampler` and `HMCSampler` into `Sampler`?
- [x] #183 Initial step size before heuristically search
- [x] #182 Numerical problem for Dirichelet

Also it may be good to implement the Algorithm 3 in the NUTS paper first before (the one without Dual Averaging), just in purpose of make one part of NUTS work first.
