### ISSUE TITLE
Roadmap for v0.3

### ISSUE THREAD

**Issue by yebai** [yebai/Turing.jl#91]
- [x] NUTS implementation #188
- [x] HMC: Transforms of ϵ for each variable #67 (replace with introducing mass matrix)
- ~~Re-define `~`: macro => function #173~~ (postponed to 0.4)
- [x] Finish: Sampler (internal) interface design #107
- [x] Substantially improve performance of HMC and Gibbs #7 
  - [x] benchmark based on NUTS only
  - [x] translate more Stan models into Turing (for NUTS): https://github.com/stan-dev/example-models
  - [x] vectorising likelihood computations #117 #255
  - [x] Time waste for constructing distributions in Distributions.jl #166
 - [x] Remove obsolete `randoc`, `randc`? #156
- [ ] Maximum a posteriori (MAP) inference. #72
- [ ] Compositional MCMC: partial refreshment of the momentum variable #189 
- ~~Allowing user to change the compiler between safe mode and fast mode~~
- [x] Support truncated distribution. #87
- [x] Refactoring code: Unify VarInfo, Trace, TaskLocalStorage #96
- [x] Refactoring code: Better gradient interface #97
- [ ] Support sampling from model in model #86
